<a href="https://colab.research.google.com/github/rrankawat/tensors-basic/blob/main/1_Dimensional_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip3 install torch

In [16]:
import torch
import numpy as np

In [10]:
i = torch.tensor([1, 2, 3, 4, 5, 6])

print(i)
print(i.dtype)

print(i[0])
print(i[1:4]) # Split
print(i[1:]) # Split

tensor([1, 2, 3, 4, 5, 6])
torch.int64
tensor(1)
tensor([2, 3, 4])
tensor([2, 3, 4, 5, 6])


In [12]:
f = torch.FloatTensor([1, 2, 3, 4, 5, 6])

print(f)
print(f.dtype)
print(f.size())

tensor([1., 2., 3., 4., 5., 6.])
torch.float32
torch.Size([6])


In [15]:
# View
# i.view(3, 2)
i.view(3, -1) # When we're not sure about no of elements in each raw

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [19]:
# Numpy array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# Converting numpy array into tensor
tensor_cnv = torch.from_numpy(arr)
print(tensor_cnv)

# Converting tensor into numpy array
numpy_cnv = tensor_cnv.numpy()
print(numpy_cnv)

[1 2 3 4 5]
tensor([1, 2, 3, 4, 5])
[1 2 3 4 5]
