<a href="https://colab.research.google.com/github/rrankawat/tensors-basic/blob/main/3_Two_Dimensional_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [5]:
# 1 D
one_d = torch.arange(0, 9)
print(one_d)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])


In [11]:
# 2 D
two_d = one_d.view(3, 3)

print(two_d)
print(two_d.dim())
print(two_d[0, 0])
print(two_d[1, 2])

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
2
tensor(0)
tensor(5)


In [13]:
# 3 D
# three_d = torch.arange(18).view(2, 3, 3)
three_d = torch.arange(18).view(3, 3, 2)
print(three_d)

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]])
